name = "William Neutron"
uid = "fffffffe-6e98-4864-9599-4133236eea7f"
version = 1.1
copyright = ""
description = "Static TML Launches Billy Nuke."
author = "loudpatches"
--icon = "/mods/BrewLAN_Gameplay/WaterGuard/mod_icon.dds"
selectable = true
enabled = true
exclusive = false
ui_only = false
before = {  }
after = {  }
